FROM alpine:latest

ARG IMAGE_VERSION
ARG BUILD_DATE
ARG IMAGE_AUTHOR

ARG PACKAGE_LABELS
LABEL package.labels="${PACKAGE_LABELS}"


LABEL version=$IMAGE_VERSION
LABEL build_date=$BUILD_DATE
LABEL author=$IMAGE_AUTHOR

COPY . /app
WORKDIR /app

CMD ["echo", "Hello from Docker! Version: $IMAGE_VERSION"]